### ISSUE TITLE
InvalidSecretKey error

### ISSUE THREAD

**Issue by zhfnjust** [KZen-networks/dlog-verifiable-enc#10]
hello, this library work fine.

but this error happened some time.

```
 node ./src/index.js

/home/hh/code/escrow-demo/node_modules/dlog-verifiable-enc/dist/lib/src/verifiable-encryption.js:23
    var proof = JSON.parse(bindings.ve_prove(encryptionKey.toString('hex'), JSON.stringify(encryptionResult.witness), JSON.stringify(encryptionResult.ciphertexts)));
                                    ^

Error: internal error in Neon module: called `Result::unwrap()` on an `Err` value: InvalidSecretKey
    at Object.prove (/home/hh/code/escrow-demo/node_modules/dlog-verifiable-enc/dist/lib/src/verifiable-encryption.js:23:37)
    at fakeKey (/home/hh/code/escrow-demo/src/index.js:67:27)
    at Object.<anonymous> (/home/hh/code/escrow-demo/src/index.js:74:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! enc-test@1.0.0 start: `node ./src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the enc-test@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hh/.npm/_logs/2021-05-15T16_52_44_428Z-debug.log

```

**Comment by zhfnjust** [comment]
and when i use node 14 to  instal this library , it failed, but success on node 10

**Comment by omershlo** [comment]
Hi @zhfnjust ! thank you for reporting. 
I believe that updating the zengo-x rust dependencies to latest will solve the first issue. 
Do you want to give it a try? 
about the second issue: we need to take a look ? 
cc: @elichai , @MatanHamilis , @survived , @oleiba  if any of you guys know?

**Comment by elichai** [comment]
Hmm I have a feeling this is related to how javascript handles `key.toString('hex')`.
in JS when you convert a number/array to hex it doesn't pad it with zeros at the start, so once in 1/256 you get 0 as your first byte which makes the hex 31 bytes instead of 32 (can be shorter than 31 if you have multiple leading zeros), 
Could you try to print `encryptionKey.toString('hex')` and see how long is it when this fails?

**Comment by zhfnjust** [comment]
privKeyEscrow `cTNBXGcyddAXbkLPniZZuPE56bpc8496b7LTZZqUTnzhv4sa4nhJ`
ucPubKeyEscrow `aeadd2d65172564fd88ad120dec321b6f50f44fa5e9ee3be48dd9cb74ed4a06477605dce9bbf2c87cc3b12a84055a874c6567e73448c92b059d9269ea98112de`
```
/home/hh/code/escrow-demo/node_modules/dlog-verifiable-enc/dist/lib/src/verifiable-encryption.js:23
    var proof = JSON.parse(bindings.ve_prove(encryptionKey.toString('hex'), JSON.stringify(encryptionResult.witness), JSON.stringify(encryptionResult.ciphertexts)));
                                    ^

Error: internal error in Neon module: called `Result::unwrap()` on an `Err` value: InvalidSecretKey
    at Object.prove (/home/hh/code/escrow-demo/node_modules/dlog-verifiable-enc/dist/lib/src/verifiable-encryption.js:23:37)
    at Object.<anonymous> (/home/hh/code/escrow-demo/src/index.js:42:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```
i use this privkey fixed, it still crash some time
